<a href="https://colab.research.google.com/github/rishisaini1223/Advance_python/blob/main/ML_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Machine Learning  ---
# Data (50) --> x(Input data), y(target data)
# x ---> x_train , x_test
# y ---> y_train , y_test
# for machine training we will pass (x_train, y_train)
# for machine testing  we pass (x_test, y_test)

# 1+1 =2
# 1+2=3
# 1+3=4

# x = (1+1, 1+2, 1+3)
# y = (2,3,4)
# x_train = (1+1,1+2)
# x_test = (1+3)
# y_train = (2,3)
# y_test = (4)

In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv('/content/covid_toy - covid_toy.csv')
# df.head(3)

   age gender  fever cough     city has_covid
0   60   Male  103.0  Mild  Kolkata        No
1   27   Male  100.0  Mild    Delhi       Yes
2   42   Male  101.0  Mild    Delhi        No

In [ ]:
df.shape

(100, 6)

In [ ]:
df.isnull().sum()

age           0
gender        0
fever        10
cough         0
city          0
has_covid     0
dtype: int64

In [ ]:
# fill null values
df['fever'] = df['fever'].fillna(df['fever'].mean())

In [ ]:
x = df.drop(columns = ['has_covid'])   # input data
# x

In [ ]:
y = df['has_covid'] # target or output data
y

0      No
1     Yes
2      No
3      No
4      No
     ...
95     No
96    Yes
97     No
98     No
99    Yes
Name: has_covid, Length: 100, dtype: object

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.2 , random_state=42)

In [ ]:
print('total data shape: ',df.shape)
print('----------------------')
print('input data shape: ',x.shape)
print('x_train data shape: ',x_train.shape)
print('x_test data shape', x_test.shape)
print('-----------------------')
print('target data shape: ', y.shape)
print('y_tarin data shape: ',y_train.shape)
print('y_test data shape: ',y_test.shape)

total data shape:  (100, 6)
----------------------
input data shape:  (100, 5)
x_train data shape:  (80, 5)
x_test data shape (20, 5)
-----------------------
target data shape:  (100,)
y_tarin data shape:  (80,)
y_test data shape:  (20,)

In [ ]:
pal = pd.read_csv('/content/placement - placement.csv')

In [ ]:
pal.head(3)

   cgpa  resume_score  placed
0  8.14          6.52       1
1  6.17          5.17       0
2  8.27          8.86       1

In [ ]:
pal.shape

(100, 3)

In [ ]:
pal.isnull().sum()

cgpa            0
resume_score    0
placed          0
dtype: int64

In [ ]:
a = pal.drop(columns= 'placed')
a.head(3)

   cgpa  resume_score
0  8.14          6.52
1  6.17          5.17
2  8.27          8.86

In [ ]:
b = pal['placed']
b.head(2)

0    1
1    0
Name: placed, dtype: int64

In [ ]:
a_train, a_test, b_train, b_test = train_test_split(a,b,test_size=0.2 , random_state=42)

In [ ]:
print('total data shape: ',pal.shape)
print('----------------------')
print('input data shape: ',a.shape)
print('x_train data shape: ',a_train.shape)
print('x_test data shape', a_test.shape)
print('-----------------------')
print('target data shape: ', b.shape)
print('y_tarin data shape: ',b_train.shape)
print('y_test data shape: ',b_test.shape)

total data shape:  (100, 3)
----------------------
input data shape:  (100, 2)
x_train data shape:  (80, 2)
x_test data shape (20, 2)
-----------------------
target data shape:  (100,)
y_tarin data shape:  (80,)
y_test data shape:  (20,)