<a href="https://colab.research.google.com/github/rishisaini1223/Advance_python/blob/main/Pandas_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [30]:
import pandas as pd

In [31]:
df = pd.read_csv("/content/covid_toy - covid_toy.csv")

In [32]:
# top data check , we will use df.head() , by default it returns top 5 rows
df.head(2)

   age gender  fever cough     city has_covid
0   60   Male  103.0  Mild  Kolkata        No
1   27   Male  100.0  Mild    Delhi       Yes

In [33]:
# bottom data check , we will use df.tail(),by default it return last 5 rows.
df.tail(3)

    age  gender  fever   cough       city has_covid
97   20  Female  101.0    Mild  Bangalore        No
98    5  Female   98.0  Strong     Mumbai        No
99   10  Female   98.0  Strong    Kolkata       Yes

In [34]:
# if you want random indexed data , then we will use df.sample().by default it will
# return single row
df.sample()

    age  gender  fever cough     city has_covid
79   48  Female  103.0  Mild  Kolkata       Yes

In [35]:
# if we want to check data type of each column . dfdtypes
df.dtypes

age            int64
gender        object
fever        float64
cough         object
city          object
has_covid     object
dtype: object

In [36]:
# if we want to check overall information then we will use df.info()
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 6 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   age        100 non-null    int64
 1   gender     100 non-null    object
 2   fever      90 non-null     float64
 3   cough      100 non-null    object
 4   city       100 non-null    object
 5   has_covid  100 non-null    object
dtypes: float64(1), int64(1), object(4)
memory usage: 4.8+ KB

In [37]:
# x = 0-100
# 50% = 50
# x = 1,2,3,4,5
# mean = (1+2+3+4+5)/5 = 15/5 = 3

In [38]:
# if you want to check statical view of data , then you can use df.describe()
df.describe()

              age       fever
count  100.000000   90.000000
mean    44.220000  100.844444
std     24.878931    2.054926
min      5.000000   98.000000
25%     20.000000   99.000000
50%     45.000000  101.000000
75%     66.500000  102.750000
max     84.000000  104.000000

In [39]:
df.head(2)

   age gender  fever cough     city has_covid
0   60   Male  103.0  Mild  Kolkata        No
1   27   Male  100.0  Mild    Delhi       Yes

In [40]:
# if you want to check missing data in df , then you will use df.isnull().sum()

In [41]:
df.isnull().sum()

age           0
gender        0
fever        10
cough         0
city          0
has_covid     0
dtype: int64

In [42]:
# s = 1,2,3,nan,5
# mean  = 2.75
# we will fill this value in missing data

In [43]:
df['fever'] = df['fever'].fillna(df['fever'].mean())

In [44]:
# df.isnull().sum()

In [45]:
df.head(1)

   age gender  fever cough     city has_covid
0   60   Male  103.0  Mild  Kolkata        No

In [46]:
# if you have categorical data , and you wnat to check total sub_categorical then
# we will use df['column_name'].value_counts()

In [47]:
df['gender'].value_counts()

gender
Female    59
Male      41
Name: count, dtype: int64

In [48]:
df['gender'] = df['gender'].map({'Female':1,'Male':0})

In [49]:
df.head(2)

   age  gender  fever cough     city has_covid
0   60       0  103.0  Mild  Kolkata        No
1   27       0  100.0  Mild    Delhi       Yes

In [50]:
df['cough'] = df['cough'].map({'Mild':1,'Strong':0})

In [51]:
df.sample()

    age  gender       fever  cough   city has_covid
10   75       1  100.844444      1  Delhi        No

In [52]:
df['has_covid'] = df['has_covid'].map({'Yes':1,'No':0})

In [54]:
df.sample(4)

    age  gender  fever  cough       city  has_covid
70   68       1  101.0      0      Delhi          0
17   40       1   98.0      0      Delhi          0
45   72       0   99.0      1  Bangalore          0
90   59       1   99.0      0      Delhi          0